name: merge_l10n
description: Merge arb files into one.
version: 0.1.0
repository: https://github.com/rIIh/merge_l10n
issue_tracker: https://github.com/rIIh/merge_l10n/issues

environment:
  sdk: ^3.1.0

dependencies:
  freezed_annotation: ^2.0.0
  equatable: ^2.0.0
  fpdart: ^1.0.0
  args: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.0.0

  build_runner: ^2.0.0
  freezed: ^2.0.0
  json_serializable: ^6.0.0
